//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DREA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.DocumentoDet = new HashSet<DocumentoDet>();
        }
    
        public int DocumentoId { get; set; }
        public string Nombre { get; set; }
        public string NroDoc { get; set; }
        public int TipoDocId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public int OficinaId { get; set; }
        public int UsuarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoDet> DocumentoDet { get; set; }
        public virtual Oficina Oficina { get; set; }
        public virtual TipoDoc TipoDoc { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
